AWSTemplateFormatVersion: '2010-09-09'
Resources:
  DevUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: DevUser
      Groups: [!Ref DevelopersGroup]
  DevelopersGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: Developers
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
