AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3AllowAllPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 's3:*'
            Resource: '*'
  S3ExplicitDenyPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Deny
            Action: 's3:*'
            Resource:
              - 'arn:aws:s3:::production-data'
              - 'arn:aws:s3:::production-data/*'
  DataScientistUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: DataScientist
      ManagedPolicyArns:
        - !Ref S3AllowAllPolicy
        - !Ref S3ExplicitDenyPolicy
